SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `estudiantes` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `NOMBRE_Y_APELLIDO` VARCHAR(255),
  `CORREO` VARCHAR(255),
  `CURSO` VARCHAR(50),
  `FECHA_DE_REGISTRO` DATE,
  `DNI` VARCHAR(20),
  `CELULAR` VARCHAR(15),
  `DIRECCION` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `estudiantes` (`ID`, `NOMBRE_Y_APELLIDO`, `CORREO`, `CURSO`, `FECHA_DE_REGISTRO`, `DNI`, `CELULAR`, `DIRECCION`) VALUES
(30, 'Luis11323232', '11232311@gmail.com', 'NodeJS', '2023-05-26', '', '', '');

ALTER TABLE `estudiantes`
  ADD INDEX `idx_curso` (`CURSO`);

ALTER TABLE `estudiantes`
  MODIFY `ID` INT AUTO_INCREMENT;
COMMIT;
